name: Main CI

on:
  push:
    branches: [main, fix/*]

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        image:
          # List: https://github.com/conan-io/conan-docker-tools
          - gcc10
          - gcc9
          - gcc8
          - gcc7
          - clang11
          - clang10
          - clang9
          - clang8
          - clang7
          - clang60
        build_type: [Debug, Release]
        exclude:
          # Bug in the optimizer
          - image: gcc9
            build_type: Release

    runs-on: ubuntu-latest
    container:
      image: conanio/${{matrix.image}}
      options: --user root

    steps:
    - uses: actions/checkout@v2
    - name: Create Build Environment
      run: cmake -E make_directory build
    - name: Install ninja
      run: type ninja || apt-get -qq update && apt-get install -y ninja-build

    - name: Configure
      working-directory: build/
      run: cmake -GNinja $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
    - name: Build
      working-directory: build/
      run: cmake --build .
    - name: Test
      working-directory: build/
      run: ctest -C ${{matrix.build_type}} --output-on-failure

  macos:
    strategy:
      fail-fast: false
      matrix:
        xcode:
            - '10'
            - '11'
            - '12'

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{matrix.xcode}}
    - name: Create Build Environment
      run: cmake -E make_directory build
    - name: Install ninja
      run: brew install ninja

    - name: Configure
      working-directory: build/
      run: cmake -GNinja $GITHUB_WORKSPACE
    - name: Build
      working-directory: build/
      run: cmake --build .
    - name: Test
      working-directory: build/
      run: ctest --output-on-failure

  windows:
    strategy:
      fail-fast: false
      matrix:
        toolset: ['v142', 'ClangCL']
        build_type: [Debug, Release]

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create Build Environment
      run: cmake -E make_directory build

    - name: Configure
      shell: bash
      working-directory: build/
      run: cmake $GITHUB_WORKSPACE -G"Visual Studio 16 2019" -T ${{matrix.toolset}}
    - name: Build
      working-directory: build/
      run: cmake --build . --config ${{matrix.build_type}}
    - name: Test
      working-directory: build/
      run: ctest -C ${{matrix.build_type}} --output-on-failure

